language: php
php:
    - 7.1
    - 7.2

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

before_install:
    # turn off xdebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester -p $PHP_BIN -c tests/php.ini tests/

after_failure:
    # print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   env: title="Lowest Dependencies" PHP_BIN=php
            install:
                - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable

        -   stage: Code Coverage
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   stage: Code Coverage


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
